// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';


var quiz = /* :: */[
  /* record */[
    /* text */"What is the name of the dance troupe formed by Dublin-born Margaret Kelly in Paris in 1932?",
    /* options : :: */[
      /* record */[/* text */"Bluebell Girls"],
      /* :: */[
        /* record */[/* text */"Daffodil Girls"],
        /* :: */[
          /* record */[/* text */"Daisy Girls"],
          /* :: */[
            /* record */[/* text */"Lily Girls"],
            /* [] */0
          ]
        ]
      ]
    ],
    /* correctAnswer *//* record */[/* text */"Bluebell Girls"]
  ],
  /* :: */[
    /* record */[
      /* text */"The small republic of San Marino is completely surrounded by which larger country?",
      /* options : :: */[
        /* record */[/* text */"India"],
        /* :: */[
          /* record */[/* text */"Iran"],
          /* :: */[
            /* record */[/* text */"Israel"],
            /* :: */[
              /* record */[/* text */"Italy"],
              /* [] */0
            ]
          ]
        ]
      ],
      /* correctAnswer *//* record */[/* text */"Italy"]
    ],
    /* :: */[
      /* record */[
        /* text */"In Treasure Island, Jim Hawkins is hiding in a barrel of what when he overhears Long John Silver's plan to take over the Hispaniola and murder its officers?",
        /* options : :: */[
          /* record */[/* text */"Apples"],
          /* :: */[
            /* record */[/* text */"Beer"],
            /* :: */[
              /* record */[/* text */"Flour"],
              /* :: */[
                /* record */[/* text */"Rum"],
                /* [] */0
              ]
            ]
          ]
        ],
        /* correctAnswer *//* record */[/* text */"Apples"]
      ],
      /* :: */[
        /* record */[
          /* text */"Something described as 'tactile' means that it relates to which of the senses?",
          /* options : :: */[
            /* record */[/* text */"Hearing"],
            /* :: */[
              /* record */[/* text */"Sight"],
              /* :: */[
                /* record */[/* text */"Taste"],
                /* :: */[
                  /* record */[/* text */"Touch"],
                  /* [] */0
                ]
              ]
            ]
          ],
          /* correctAnswer *//* record */[/* text */"Touch"]
        ],
        /* [] */0
      ]
    ]
  ]
];

exports.quiz = quiz;
/* No side effect */
