// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


function resolveRoute(route) {
  if (route) {
    return "/quiz";
  } else {
    return "/";
  }
}

exports.resolveRoute = resolveRoute;
/* No side effect */
