// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/lib/js/src/Json_decode.bs.js");

function answer(json) {
  return /* record */[/* text */Json_decode.field("text", Json_decode.string, json)];
}

function answerList(json) {
  return Json_decode.list(answer, json);
}

function question(json) {
  return /* record */[
          /* text */Json_decode.field("text", Json_decode.string, json),
          /* options */Json_decode.field("options", answerList, json),
          /* correctAnswer */Json_decode.optional((function (param) {
                  return Json_decode.field("correctAnswer", answer, param);
                }), json)
        ];
}

function quiz(json) {
  return Json_decode.list(question, json);
}

function result(json) {
  return /* record */[
          /* numCorrect */Json_decode.field("numCorrect", Json_decode.$$int, json),
          /* totalQuestions */Json_decode.field("totalQuestions", Json_decode.$$int, json)
        ];
}

exports.answer = answer;
exports.answerList = answerList;
exports.question = question;
exports.quiz = quiz;
exports.result = result;
/* No side effect */
