// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Json_encode = require("@glennsl/bs-json/lib/js/src/Json_encode.bs.js");

function answer(param) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "text",
                param[/* text */0]
              ],
              /* [] */0
            ]);
}

function answerList(answers) {
  return Json_encode.list(answer, answers);
}

function question(param) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "text",
                param[/* text */0]
              ],
              /* :: */[
                /* tuple */[
                  "options",
                  Json_encode.list(answer, param[/* options */1])
                ],
                /* :: */[
                  /* tuple */[
                    "correctAnswer",
                    null
                  ],
                  /* [] */0
                ]
              ]
            ]);
}

function quiz(quiz$1) {
  return Json_encode.list(question, quiz$1);
}

function result(param) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "numCorrect",
                param[/* numCorrect */0]
              ],
              /* :: */[
                /* tuple */[
                  "totalQuestions",
                  param[/* totalQuestions */1]
                ],
                /* [] */0
              ]
            ]);
}

exports.answer = answer;
exports.answerList = answerList;
exports.question = question;
exports.quiz = quiz;
exports.result = result;
/* Json_encode Not a pure module */
